### ISSUE TITLE
Where's node_modules supposed to be?

### ISSUE THREAD

**Issue by elie222** [spencercarli/react-native-meteor-accounts#3]
I'm trying to run the iOS app and get this error:

```
Error: Cannot find module '.../react-native-meteor-accounts/RNFacebookExample/node_modules/react-native/local-cli/cli.js'
```

**Comment by elie222** [comment]
OK I ran `npm install --save react-native-fbsdk`. Now I have other issues

**Comment by elie222** [comment]
The issue is now that: `node_modules/react-native/local-cli/cli.js` doesn't exist. The folder `local-cli` doesn't exist.

**Comment by elie222** [comment]
After also doing `npm install --save react-native-fbsdklogin` and `pod install` I now have this error and really not sure what's up:

```
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ios"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! RNFacebookExample@0.0.1 ios: `open ios/RNFacebookExample.xcworkspace/ && npm start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the RNFacebookExample@0.0.1 ios script 'open ios/RNFacebookExample.xcworkspace/ && npm start'.
npm ERR! This is most likely a problem with the RNFacebookExample package,
npm ERR! not with npm itself.
```

**Comment by elie222** [comment]
Here's the npm blog stuff:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'ios' ]
2 info using npm@2.14.7
3 info using node@v4.2.3
4 verbose run-script [ 'preios', 'ios', 'postios' ]
5 info preios RNFacebookExample@0.0.1
6 info ios RNFacebookExample@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info RNFacebookExample@0.0.1 Failed to exec ios script
9 verbose stack Error: RNFacebookExample@0.0.1 ios: `open ios/RNFacebookExample.xcworkspace/ && npm start`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid RNFacebookExample@0.0.1
```

**Comment by spencercarli** [comment]
You should run `npm install` from inside the `RNFacebookExample` folder.
